<?php
// Modify usertest.php
	$agentName = array (
		'abarrett'   => 'Amy Barrett',
		'almullins'  => 'Alquici Mullins',
		'ataylor'    => 'Ambria Taylor',
		'avanegas'   => 'Alma Vanegas',
		'bzertuche'  => 'Brayden Zertuche',
		'chmoran'    => 'Titan',
		'dbates'     => 'Darian Bates',
		'dbustamente'=> 'Dakota Bustamente',
		'dgarcia'    => 'Dago Garcia',
		'ddewitt'    => 'Don Dewitt',
		'ddecoux'    => 'Deborah Decoux',
		'gcarroll'   => 'Grady Carroll',
		'hportillo'  => 'Hugo Portillo',
		'jbrooks'    => 'Jennifer Brooks',
		'jemcavin'   => 'Jessica McAvin',
		'jmann'      => 'Jasmine Mann',
		'jweiss'     => 'Jennifer Weiss',
		'jsaldana'   => 'Jose Saldana',
		'jvalle'     => 'Jonathan Valle',
		'kedavid'    => 'Kerry David',
		'kdieppue'   => 'Djoko Dieppue',
		'klafitte'   => 'Devon Shanice Lafitte',
		'knesbitt'   => 'Kassandra Nesbitt',
		'mawilliams' => 'Maelan Williams',
		'mdiaz'      => 'Mario Diaz',
		'mfernandez' => 'Melissa Fernandez',
		'mtorres'    => 'Miguel Torres',
		'oislam'     => 'Ozair Islam',
		'pharper'    => 'Patricia Harper',
		'rhagemann'  => 'Richard Hagemann',
		'rpianesi'   => 'Ryan Pianesi',
		'rrodriguez' => 'Rene Rodriguez',
		'sdavidson'  => 'Sherry Davidson',
		'smintz'     => 'Sharron Mintz',
		'ssaucedo'   => 'Shally Saucedo',
		'thess'      => 'thess',
		'tcedillo'   => 'Thaddeus Cedillo',
		'tkalinec'   => 'Treigh Kalinec',
		'toneal'     => 'Theodore ONeal',
		'twashington'=> 'twashington',
		'veme'       => 'Victoria Eme'
	);

?>